### ISSUE TITLE
fine-tuned weights

### ISSUE THREAD

**Issue by Howardyangyixuan** [FENGGENYU/CAPRI-Net#6]
Hi GenYu,
Thanks for your fascinating work for giving us many idea both on network structure and training method.
We're conducting some comparasions with your work. Could you please release your fine-tuned weights so we can make it more fair?
Thanks a lot!

**Comment by Sangminhong** [comment]
@Howardyangyixuan I am wondering whether it was possible to reproduce the qualitative results. Even after fine-tuning, the result that I've got doesn't seem to be right.

**Comment by FENGGENYU** [comment]
The fine-tuned weights are quite large, I don't have plan to release them now. The fine-tuning of 1000 shapes will take about 2-3 days, you can run our codes to get the results.

**Comment by Howardyangyixuan** [comment]
OK. Thanks for your reply.
