### ISSUE TITLE
is it need to train all the stages？

### ISSUE THREAD

**Issue by bigKoki** [FENGGENYU/CAPRI-Net#8]
I see that 3 types of training strategy ，if i want to trian this model，do I need to train all three stages once？
thanks very much！！！

**Comment by FENGGENYU** [comment]
Hi, Sorry about the late reply.

You could just train the first stage.

The later two stages are used during fine-tuning.

**Comment by bigKoki** [comment]
thanks for your reply！！！
wish you have a good day
